language: php

php:
  - "nightly"
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"

install:
  - if [[ $TRAVIS_PHP_VERSION > '7.1' ]]; then wget -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-7.phar; fi
  - if [[ $TRAVIS_PHP_VERSION > '7.1' ]]; then chmod 755 ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit; fi
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - test -z "$DISABLE_FUNCTIONS" || echo "disable_functions=$DISABLE_FUNCTIONS" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpunit --version
script:
  - phpunit --verbose --stderr